### ISSUE TITLE
What do you mean by copy the ROM's?

### ISSUE THREAD

**Issue by arccoxx** [kuz/DeepMind-Atari-Deep-Q-Learner#3]
Hi.

Ive been having some trouble getting this running. 

Here's what Ive done so far:
I have run the install_dependencies file but the torch folder is empty:

![screen shot 2015-07-29 at 7 05 27 pm](https://cloud.githubusercontent.com/assets/2307341/8972131/f664ea5a-3624-11e5-8126-df9a75a63154.png)

I then tried running the run_cpu and run_gpu files in terminal. Like so:

![screen shot 2015-07-29 at 7 09 31 pm](https://cloud.githubusercontent.com/assets/2307341/8972176/677e06cc-3625-11e5-8b0d-12c1ccdda292.png)

I dont understand what "copy the rom file in ROM's" means. If you could clarify this step or identify whats preventing me from running the software that would be great! 

Thanks!

**Comment by kuz** [comment]
Hi,

this problem is fixed now. Pull the repository, and run ./install_dependecies.sh again, it will install missing things.

By "copy the rom file" I mean that if you want to try other game than Breakout you need to find game.bin online and put it into the "roms" directory. But for the Breakout the ROM is already included in the repository, so this is not what was causing your problem.
